name: test_wokflow

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  edit_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    
    - name: Delete and create a branch
      run: |
        git branch -D "Atlas_adoption" || true
        git checkout -b "Atlas_adoption"
          

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install configparser
        pip install elementpath
        pip install lxml

    - name: Run script
      run: python Hackathon_demo/config.py

    - name: Commit changes
      run: |
        git commit -am "Update file"
        git push -f origin "Atlas_adoption"
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: "Make changes"
        body: "This PR makes changes."
        branch: "main"
        base: "Atlas_adoption"
