name: test_wokflow

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  edit_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    
    - name: Delete and create a branch
      run: |
        git branch -D "Atlas_adoption_1" || true
        git checkout -b "Atlas_adoption_1"
          

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install configparser
        pip install elementpath
        pip install lxml

    - name: Run script
      run: python Hackathon_demo/config.py

    - name: Commit changes
      run: |
        git add .
        git commit -m "Update file"
        git push -f origin "Atlas_adoption_1"
    
    - name: Create Pull Request
      uses: CasperWA/push-protected@v2
      with:
        token: ${{ secrets.PUSH_TO_PROTECTED_BRANCH }}
        branch: main
        unprotect_reviews: true
