name: test_wokflow

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  edit_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create pull request
      id: Atlas_adoption_1
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "main"
        pr_title: "feat: PLACEHOLDER TITLE"
        pr_draft: true

    - name: Set up Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
          

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install configparser
        pip install elementpath
        pip install lxml

    - name: Run script
      run: python Hackathon_demo/config.py

    - name: Commit changes
      run: |
        git add .
        git commit -m "Update file"
        git push -f origin "Atlas_adoption_1"   
